package pktmsg_test

import (
	"testing"
	"time"

	"github.com/go-test/deep"

	"steve.rothskeller.net/packet/pktmsg"
)

var parseMessageTests = []struct {
	name   string
	rawmsg string
	want   pktmsg.ParsedMessage
}{
	{
		"unparseable message",
		"XXX",
		&pktmsg.RxBase{
			ParseError: `malformed MIME header: missing colon: "XXX"`,
		},
	},
	{
		"bounce envelope",
		"From  Wed Dec  1 08:04:30 2021\nFrom: notthis@nowhere\nSubject: Bounce\n\nBounce\n",
		&pktmsg.RxBase{
			DeliveryTime: time.Date(2021, 12, 1, 8, 4, 30, 0, time.Local),
			SubjectLine:  "Bounce",
			Body:         "Bounce\n",
		},
	},
	{
		"bounce without envelope",
		"Return-Path: <>\nReceived: blah; Wed, 1 Dec 2021 08:04:30 -0800\nFrom: notthis@nowhere\nSubject: Bounce\n\nBounce\n",
		&pktmsg.RxBase{
			DeliveryTime: time.Date(2021, 12, 1, 8, 4, 30, 0, time.Local),
			SubjectLine:  "Bounce",
			Body:         "Bounce\n",
		},
	},
	{
		"no plain text",
		"From nobody@nowhere\nContent-Type: text/html\nSubject: test\n\n<div></div>\n",
		&pktmsg.RxMessage{
			RxBase: pktmsg.RxBase{
				ReturnAddress: "nobody@nowhere",
				SubjectLine:   "test",
				NotPlainText:  true,
			},
			Subject: "test",
		},
	},
	{
		"multipart",
		"From nobody@nowhere\nContent-Type: multipart/related; boundary=\"b1\"\nSubject: test\n\n\n--b1\nContent-Type: text/html\n\n<div>not this</div>\n\n--b1\nContent-Type: multipart/alternative; boundary=\"b2\"\n\n\n--b2\nContent-Type: text/html\n\n<div>not this either</div>\n\n--b2\nContent-Type: text/plain\n\nThis!\n\n--b2--\n\n--b1--\n",
		&pktmsg.RxMessage{
			RxBase: pktmsg.RxBase{
				ReturnAddress: "nobody@nowhere",
				SubjectLine:   "test",
				NotPlainText:  true,
				Body:          "This!\n",
			},
			Subject: "test",
		},
	},
	{
		"base64 encoding",
		"From nobody@nowhere\nContent-Transfer-Encoding: base64\nSubject: test\n\nSGVsbG8sIHdvcmxkIQo=\n",
		&pktmsg.RxMessage{
			RxBase: pktmsg.RxBase{
				ReturnAddress: "nobody@nowhere",
				SubjectLine:   "test",
				NotPlainText:  true,
				Body:          "Hello, world!\n",
			},
			Subject: "test",
		},
	},
	{
		"quoted-printable encoding",
		"From nobody@nowhere\nContent-Transfer-Encoding: quoted-printable\nSubject: test\n\nHello, =\nworld=21\n",
		&pktmsg.RxMessage{
			RxBase: pktmsg.RxBase{
				ReturnAddress: "nobody@nowhere",
				SubjectLine:   "test",
				NotPlainText:  true,
				Body:          "Hello, world!\n",
			},
			Subject: "test",
		},
	},
	{
		"outpost encoded",
		"From nobody@nowhere\nSubject: test\n\n!B64!SGVsbG8sIHdvcmxkIQo=\n",
		&pktmsg.RxMessage{
			RxBase: pktmsg.RxBase{
				ReturnAddress: "nobody@nowhere",
				SubjectLine:   "test",
				NotPlainText:  true,
				Body:          "Hello, world!\n",
			},
			Subject: "test",
		},
	},
	{
		"outpost flags",
		"From nobody@nowhere\nSubject: test\n\n!URG!!RDR!!RRR!Hello, world!\n",
		&pktmsg.RxMessage{
			RxBase: pktmsg.RxBase{
				ReturnAddress:          "nobody@nowhere",
				SubjectLine:            "test",
				OutpostUrgent:          true,
				RequestDeliveryReceipt: true,
				RequestReadReceipt:     true,
				Body:                   "Hello, world!\n",
			},
			Subject: "test",
		},
	},
	{
		"plain text without SCCo fields",
		"From nobody@nowhere\nSubject: test\n\nHello, world!\n",
		&pktmsg.RxMessage{
			RxBase: pktmsg.RxBase{
				ReturnAddress: "nobody@nowhere",
				SubjectLine:   "test",
				Body:          "Hello, world!\n",
			},
			Subject: "test",
		},
	},
	{
		"plain text with SCCo fields",
		"From a6aaa@a6bbb.ampr.org\nSubject: AAA-111_R_test\n\nHello, world!\n",
		&pktmsg.RxMessage{
			RxBase: pktmsg.RxBase{
				ReturnAddress: "a6aaa@a6bbb.ampr.org",
				SubjectLine:   "AAA-111_R_test",
				Body:          "Hello, world!\n",
			},
			FromCallSign:      "A6AAA",
			FromBBS:           "A6BBB",
			MessageNumber:     "AAA-111",
			HandlingOrderCode: "R",
			HandlingOrder:     pktmsg.HandlingRoutine,
			Subject:           "test",
		},
	},
	{
		"old subject with severity",
		"From nobody@nowhere\nSubject: AAA-111_E/R_test\n\nHello, world!\n",
		&pktmsg.RxMessage{
			RxBase: pktmsg.RxBase{
				ReturnAddress: "nobody@nowhere",
				SubjectLine:   "AAA-111_E/R_test",
				Body:          "Hello, world!\n",
			},
			MessageNumber:     "AAA-111",
			SeverityCode:      "E",
			Severity:          pktmsg.SeverityEmergency,
			HandlingOrderCode: "R",
			HandlingOrder:     pktmsg.HandlingRoutine,
			Subject:           "test",
		},
	},
	{
		"delivery receipt",
		"From nobody@nowhere\nSubject: DELIVERED: subject\n\n!LMI!AAA-111!DR!2021-12-18 10:00:00\nblah\n",
		&pktmsg.RxDeliveryReceipt{
			RxBase: pktmsg.RxBase{
				ReturnAddress: "nobody@nowhere",
				SubjectLine:   "DELIVERED: subject",
				Body:          "!LMI!AAA-111!DR!2021-12-18 10:00:00\nblah\n",
			},
			DeliveredSubject: "subject",
			LocalMessageID:   "AAA-111",
			DeliveredTime:    time.Date(2021, 12, 18, 10, 0, 0, 0, time.Local),
		},
	},
	{
		"read receipt",
		"From nobody@nowhere\nSubject: READ: subject\n\n!RR!2021-12-18 10:00:00\nblah\n",
		&pktmsg.RxReadReceipt{
			RxBase: pktmsg.RxBase{
				ReturnAddress: "nobody@nowhere",
				SubjectLine:   "READ: subject",
				Body:          "!RR!2021-12-18 10:00:00\nblah\n",
			},
			ReadSubject: "subject",
			ReadTime:    time.Date(2021, 12, 18, 10, 0, 0, 0, time.Local),
		},
	},
	{
		"unknown PackItForms form",
		"From nobody@nowhere\nSubject: test\n\n!SCCoPIFO!\n#T: unknown.html\n#V: 3.2-2.0\n1.: [Field]\n!/ADDON!\n",
		&pktmsg.RxForm{
			RxMessage: pktmsg.RxMessage{
				RxBase: pktmsg.RxBase{
					ReturnAddress: "nobody@nowhere",
					SubjectLine:   "test",
					Body:          "!SCCoPIFO!\n#T: unknown.html\n#V: 3.2-2.0\n1.: [Field]\n!/ADDON!\n",
				},
				Subject: "test",
			},
			FormHTML:    "unknown.html",
			PIFOVersion: "3.2",
			FormVersion: "2.0",
			Fields:      map[string]string{"1.": "Field"},
		},
	},
	{
		"PackItForms field escapes",
		"From nobody@nowhere\nSubject: test\n\n!SCCoPIFO!\n#T: unknown.html\n#V: 3.2-2.0\nX: [``] \\\\a\\n`]]]\n!/ADDON!\n",
		&pktmsg.RxForm{
			RxMessage: pktmsg.RxMessage{
				RxBase: pktmsg.RxBase{
					ReturnAddress: "nobody@nowhere",
					SubjectLine:   "test",
					Body:          "!SCCoPIFO!\n#T: unknown.html\n#V: 3.2-2.0\nX: [``] \\\\a\\n`]]]\n!/ADDON!\n",
				},
				Subject: "test",
			},
			FormHTML:    "unknown.html",
			PIFOVersion: "3.2",
			FormVersion: "2.0",
			Fields:      map[string]string{"X": "`] \\a\n`"},
		},
	},
	{
		"ICS-213 form",
		"From nobody@nowhere\nSubject: AAA-111_R_ICS213_subject\n\n!SCCoPIFO!\n#T: form-ics213.html\n#V: 3.2-2.1\nMsgNo: [AAA-111]\n1a.: [12/18/2021]\n4.: [OTHER]\n5.: [ROUTINE]\n6a.: [No]\n6b.: [Yes]\n6d.: [never]\n6c.: [checked]\n1b.: [12:34]\n7.: [topos]\n8.: [frompos]\n9a.: [toloc]\n9b.: [fromloc]\nToName: [toname]\nFmName: [fromname]\nToTel: [totel]\nFmTel: [fromtel]\n10.: [subject]\n11.: [ref]\n12.: [message]\nOpRelayRcvd: [rr]\nOpRelaySent: [rs]\nRec-Sent: [sender]\nOpCall: [A6AAA]\nOpName: [Fred Flintstone]\nMethod: [Other]\nOther: [Packet]\nOpDate: [12/18/2021]\nOpTime: [09:54]\n!/ADDON!\n",
		&pktmsg.RxICS213Form{
			RxForm: pktmsg.RxForm{
				RxMessage: pktmsg.RxMessage{
					RxBase: pktmsg.RxBase{
						ReturnAddress: "nobody@nowhere",
						SubjectLine:   "AAA-111_R_ICS213_subject",
						Body:          "!SCCoPIFO!\n#T: form-ics213.html\n#V: 3.2-2.1\nMsgNo: [AAA-111]\n1a.: [12/18/2021]\n4.: [OTHER]\n5.: [ROUTINE]\n6a.: [No]\n6b.: [Yes]\n6d.: [never]\n6c.: [checked]\n1b.: [12:34]\n7.: [topos]\n8.: [frompos]\n9a.: [toloc]\n9b.: [fromloc]\nToName: [toname]\nFmName: [fromname]\nToTel: [totel]\nFmTel: [fromtel]\n10.: [subject]\n11.: [ref]\n12.: [message]\nOpRelayRcvd: [rr]\nOpRelaySent: [rs]\nRec-Sent: [sender]\nOpCall: [A6AAA]\nOpName: [Fred Flintstone]\nMethod: [Other]\nOther: [Packet]\nOpDate: [12/18/2021]\nOpTime: [09:54]\n!/ADDON!\n",
					},
					MessageNumber:     "AAA-111",
					HandlingOrderCode: "R",
					HandlingOrder:     pktmsg.HandlingRoutine,
					FormName:          "ICS213",
					Subject:           "subject",
				},
				FormHTML:    "form-ics213.html",
				PIFOVersion: "3.2",
				FormVersion: "2.1",
				Fields: map[string]string{
					"MsgNo":       "AAA-111",
					"1a.":         "12/18/2021",
					"4.":          "OTHER",
					"5.":          "ROUTINE",
					"6a.":         "No",
					"6b.":         "Yes",
					"6d.":         "never",
					"6c.":         "checked",
					"1b.":         "12:34",
					"7.":          "topos",
					"8.":          "frompos",
					"9a.":         "toloc",
					"9b.":         "fromloc",
					"ToName":      "toname",
					"FmName":      "fromname",
					"ToTel":       "totel",
					"FmTel":       "fromtel",
					"10.":         "subject",
					"11.":         "ref",
					"12.":         "message",
					"OpRelayRcvd": "rr",
					"OpRelaySent": "rs",
					"Rec-Sent":    "sender",
					"OpCall":      "A6AAA",
					"OpName":      "Fred Flintstone",
					"Method":      "Other",
					"Other":       "Packet",
					"OpDate":      "12/18/2021",
					"OpTime":      "09:54",
				},
			},
			MessageNumber:    "AAA-111",
			Date:             "12/18/2021",
			Severity:         pktmsg.SeverityOther,
			HandlingOrder:    pktmsg.HandlingRoutine,
			TakeAction:       "No",
			Reply:            "Yes",
			ReplyBy:          "never",
			FYI:              true,
			Time:             "12:34",
			DateTime:         time.Date(2021, 12, 18, 12, 34, 0, 0, time.Local),
			ToICSPosition:    "topos",
			FromICSPosition:  "frompos",
			ToLocation:       "toloc",
			FromLocation:     "fromloc",
			ToName:           "toname",
			FromName:         "fromname",
			ToTelephone:      "totel",
			FromTelephone:    "fromtel",
			Subject:          "subject",
			Reference:        "ref",
			MessageBody:      "message",
			RelayReceived:    "rr",
			RelaySent:        "rs",
			ReceiverSender:   "sender",
			OperatorCallSign: "A6AAA",
			OperatorName:     "Fred Flintstone",
			OperatorMethod:   "Packet",
			OperatorDate:     "12/18/2021",
			OperatorTime:     "09:54",
			OperatorDateTime: time.Date(2021, 12, 18, 9, 54, 0, 0, time.Local),
		},
	},
	{
		"EOC-213RR form",
		"From nobody@nowhere\nSubject: AAA-111_P_EOC213RR_incident\n\n!SCCoPIFO!\n#T: form-scco-eoc-213rr.html\n#V: 3.2-2.3\nMsgNo: [AAA-111]\n1a.: [12/18/2021]\n1b.: [12:34]\n5.: [PRIORITY]\n7a.: [topos]\n8a.: [frompos]\n7b.: [toloc]\n8b.: [fromloc]\n7c.: [toname]\n8c.: [fromname]\n7d.: [tocon]\n8d.: [fromcon]\n21.: [incident]\n22.: [12/18/2021]\n23.: [12:30]\n25.: [req]\n26.: [prep]\n27.: [app]\n28.: [qty]\n29.: [desc]\n30.: [arr]\n31.: [High]\n32.: [cost]\n33.: [delto]\n34.: [delloc]\n35.: [sub]\n36a.: [checked]\n36b.: [checked]\n36c.: [checked]\n36d.: [fuel]\n36e.: [checked]\n36f.: [checked]\n36g.: [checked]\n36h.: [checked]\n36i.: [checked]\n37.: [instr]\nOpRelayRcvd: [rr]\nOpRelaySent: [rs]\nOpName: [Fred Flintstone]\nOpCall: [A6AAA]\nOpDate: [12/18/2021]\nOpTime: [10:25]\n!/ADDON!\n",
		&pktmsg.RxEOC213RRForm{
			RxSCCoForm: pktmsg.RxSCCoForm{
				RxForm: pktmsg.RxForm{
					RxMessage: pktmsg.RxMessage{
						RxBase: pktmsg.RxBase{
							ReturnAddress: "nobody@nowhere",
							SubjectLine:   "AAA-111_P_EOC213RR_incident",
							Body:          "!SCCoPIFO!\n#T: form-scco-eoc-213rr.html\n#V: 3.2-2.3\nMsgNo: [AAA-111]\n1a.: [12/18/2021]\n1b.: [12:34]\n5.: [PRIORITY]\n7a.: [topos]\n8a.: [frompos]\n7b.: [toloc]\n8b.: [fromloc]\n7c.: [toname]\n8c.: [fromname]\n7d.: [tocon]\n8d.: [fromcon]\n21.: [incident]\n22.: [12/18/2021]\n23.: [12:30]\n25.: [req]\n26.: [prep]\n27.: [app]\n28.: [qty]\n29.: [desc]\n30.: [arr]\n31.: [High]\n32.: [cost]\n33.: [delto]\n34.: [delloc]\n35.: [sub]\n36a.: [checked]\n36b.: [checked]\n36c.: [checked]\n36d.: [fuel]\n36e.: [checked]\n36f.: [checked]\n36g.: [checked]\n36h.: [checked]\n36i.: [checked]\n37.: [instr]\nOpRelayRcvd: [rr]\nOpRelaySent: [rs]\nOpName: [Fred Flintstone]\nOpCall: [A6AAA]\nOpDate: [12/18/2021]\nOpTime: [10:25]\n!/ADDON!\n",
						},
						MessageNumber:     "AAA-111",
						HandlingOrderCode: "P",
						HandlingOrder:     pktmsg.HandlingPriority,
						FormName:          "EOC213RR",
						Subject:           "incident",
					},
					FormHTML:    "form-scco-eoc-213rr.html",
					PIFOVersion: "3.2",
					FormVersion: "2.3",
					Fields: map[string]string{
						"MsgNo":       "AAA-111",
						"1a.":         "12/18/2021",
						"1b.":         "12:34",
						"5.":          "PRIORITY",
						"7a.":         "topos",
						"8a.":         "frompos",
						"7b.":         "toloc",
						"8b.":         "fromloc",
						"7c.":         "toname",
						"8c.":         "fromname",
						"7d.":         "tocon",
						"8d.":         "fromcon",
						"21.":         "incident",
						"22.":         "12/18/2021",
						"23.":         "12:30",
						"25.":         "req",
						"26.":         "prep",
						"27.":         "app",
						"28.":         "qty",
						"29.":         "desc",
						"30.":         "arr",
						"31.":         "High",
						"32.":         "cost",
						"33.":         "delto",
						"34.":         "delloc",
						"35.":         "sub",
						"36a.":        "checked",
						"36b.":        "checked",
						"36c.":        "checked",
						"36d.":        "fuel",
						"36e.":        "checked",
						"36f.":        "checked",
						"36g.":        "checked",
						"36h.":        "checked",
						"36i.":        "checked",
						"37.":         "instr",
						"OpRelayRcvd": "rr",
						"OpRelaySent": "rs",
						"OpName":      "Fred Flintstone",
						"OpCall":      "A6AAA",
						"OpDate":      "12/18/2021",
						"OpTime":      "10:25",
					},
				},
				OriginMessageNumber: "AAA-111",
				Date:                "12/18/2021",
				Time:                "12:34",
				DateTime:            time.Date(2021, 12, 18, 12, 34, 0, 0, time.Local),
				HandlingOrder:       pktmsg.HandlingPriority,
				ToICSPosition:       "topos",
				FromICSPosition:     "frompos",
				ToLocation:          "toloc",
				FromLocation:        "fromloc",
				ToName:              "toname",
				FromName:            "fromname",
				ToContactInfo:       "tocon",
				FromContactInfo:     "fromcon",
				RelayReceived:       "rr",
				RelaySent:           "rs",
				OperatorName:        "Fred Flintstone",
				OperatorCallSign:    "A6AAA",
				OperatorDate:        "12/18/2021",
				OperatorTime:        "10:25",
				OperatorDateTime:    time.Date(2021, 12, 18, 10, 25, 0, 0, time.Local),
			},
			IncidentName:             "incident",
			DateInitiated:            "12/18/2021",
			TimeInitiated:            "12:30",
			DateTimeInitiated:        time.Date(2021, 12, 18, 12, 30, 0, 0, time.Local),
			RequestedBy:              "req",
			PreparedBy:               "prep",
			ApprovedBy:               "app",
			QtyUnit:                  "qty",
			ResourceDescription:      "desc",
			Arrival:                  "arr",
			Priority:                 "High",
			EstimatedCost:            "cost",
			DeliverTo:                "delto",
			DeliverToLocation:        "delloc",
			SuggestedSources:         "sub",
			RequireEquipmentOperator: true,
			RequireLodging:           true,
			RequireFuel:              true,
			FuelRequirement:          "fuel",
			RequirePower:             true,
			RequireMeals:             true,
			RequireMaintenance:       true,
			RequireWater:             true,
			RequireOther:             true,
			SpecialInstructions:      "instr",
		},
	},
	{
		"MuniStat form",
		"From nobody@nowhere\nSubject: AAA-111_I_MuniStat_Sunnyvale\n\n!SCCoPIFO!\n#T: form-oa-muni-status.html\n#V: 3.2-2.1\nMsgNo: [AAA-111]\n1a.: [12/18/2021]\n1b.: [12:34]\n5.: [IMMEDIATE]\n7a.: [topos]\n8a.: [frompos]\n7b.: [toloc]\n8b.: [fromloc]\n7c.: [toname]\n8c.: [fromname]\n7d.: [tocon]\n8d.: [fromcon]\n19.: [Update]\n21.: [Sunnyvale]\n23.: [1111111111]\n24.: [2222222222]\n25.: [pecn]\n26.: [3333333333]\n27.: [secn]\n28.: [4444444444]\n29.: [Open]\n30.: [01/01/2021]\n31.: [13:00]\n32.: [02/02/2021]\n33.: [14:00]\n34.: [Yes]\n35.: [Normal]\n36.: [03/03/2021]\n37.: [15:00]\n38.: [04/04/2021]\n39.: [16:00]\n40.: [Yes]\n99.: [pony express]\n41.0.: [Unknown]\n41.1.: [a]\n42.0.: [Normal]\n42.1.: [b]\n43.0.: [Problem]\n43.1.: [c]\n44.0.: [Failure]\n44.1.: [e]\n45.0.: [Delayed]\n45.1.: [f]\n46.0.: [Closed]\n46.1.: [g]\n47.0.: [Early Out]\n47.1.: [h]\n48.0.: [Unknown]\n48.1.: [i]\n49.0.: [Unknown]\n49.1.: [j]\n50.0.: [Unknown]\n50.1.: [k]\n51.0.: [Unknown]\n51.1.: [l]\n52.0.: [Unknown]\n52.1.: [m]\n53.0.: [Unknown]\n53.1.: [n]\n54.0.: [Unknown]\n54.1.: [o]\n55.0.: [Unknown]\n55.1.: [p]\n56.0.: [Unknown]\n56.1.: [q]\nOpRelayRcvd: [rr]\nOpRelaySent: [rs]\nOpName: [Fred Flintstone]\nOpCall: [A6AAA]\nOpDate: [12/18/2021]\nOpTime: [10:51]\n!/ADDON!\n",
		&pktmsg.RxMuniStatForm{
			RxSCCoForm: pktmsg.RxSCCoForm{
				RxForm: pktmsg.RxForm{
					RxMessage: pktmsg.RxMessage{
						RxBase: pktmsg.RxBase{
							ReturnAddress: "nobody@nowhere",
							SubjectLine:   "AAA-111_I_MuniStat_Sunnyvale",
							Body:          "!SCCoPIFO!\n#T: form-oa-muni-status.html\n#V: 3.2-2.1\nMsgNo: [AAA-111]\n1a.: [12/18/2021]\n1b.: [12:34]\n5.: [IMMEDIATE]\n7a.: [topos]\n8a.: [frompos]\n7b.: [toloc]\n8b.: [fromloc]\n7c.: [toname]\n8c.: [fromname]\n7d.: [tocon]\n8d.: [fromcon]\n19.: [Update]\n21.: [Sunnyvale]\n23.: [1111111111]\n24.: [2222222222]\n25.: [pecn]\n26.: [3333333333]\n27.: [secn]\n28.: [4444444444]\n29.: [Open]\n30.: [01/01/2021]\n31.: [13:00]\n32.: [02/02/2021]\n33.: [14:00]\n34.: [Yes]\n35.: [Normal]\n36.: [03/03/2021]\n37.: [15:00]\n38.: [04/04/2021]\n39.: [16:00]\n40.: [Yes]\n99.: [pony express]\n41.0.: [Unknown]\n41.1.: [a]\n42.0.: [Normal]\n42.1.: [b]\n43.0.: [Problem]\n43.1.: [c]\n44.0.: [Failure]\n44.1.: [e]\n45.0.: [Delayed]\n45.1.: [f]\n46.0.: [Closed]\n46.1.: [g]\n47.0.: [Early Out]\n47.1.: [h]\n48.0.: [Unknown]\n48.1.: [i]\n49.0.: [Unknown]\n49.1.: [j]\n50.0.: [Unknown]\n50.1.: [k]\n51.0.: [Unknown]\n51.1.: [l]\n52.0.: [Unknown]\n52.1.: [m]\n53.0.: [Unknown]\n53.1.: [n]\n54.0.: [Unknown]\n54.1.: [o]\n55.0.: [Unknown]\n55.1.: [p]\n56.0.: [Unknown]\n56.1.: [q]\nOpRelayRcvd: [rr]\nOpRelaySent: [rs]\nOpName: [Fred Flintstone]\nOpCall: [A6AAA]\nOpDate: [12/18/2021]\nOpTime: [10:51]\n!/ADDON!\n",
						},
						MessageNumber:     "AAA-111",
						HandlingOrderCode: "I",
						HandlingOrder:     pktmsg.HandlingImmediate,
						FormName:          "MuniStat",
						Subject:           "Sunnyvale",
					},
					FormHTML:    "form-oa-muni-status.html",
					PIFOVersion: "3.2",
					FormVersion: "2.1",
					Fields: map[string]string{
						"MsgNo":       "AAA-111",
						"1a.":         "12/18/2021",
						"1b.":         "12:34",
						"5.":          "IMMEDIATE",
						"7a.":         "topos",
						"8a.":         "frompos",
						"7b.":         "toloc",
						"8b.":         "fromloc",
						"7c.":         "toname",
						"8c.":         "fromname",
						"7d.":         "tocon",
						"8d.":         "fromcon",
						"19.":         "Update",
						"21.":         "Sunnyvale",
						"23.":         "1111111111",
						"24.":         "2222222222",
						"25.":         "pecn",
						"26.":         "3333333333",
						"27.":         "secn",
						"28.":         "4444444444",
						"29.":         "Open",
						"30.":         "01/01/2021",
						"31.":         "13:00",
						"32.":         "02/02/2021",
						"33.":         "14:00",
						"34.":         "Yes",
						"35.":         "Normal",
						"36.":         "03/03/2021",
						"37.":         "15:00",
						"38.":         "04/04/2021",
						"39.":         "16:00",
						"40.":         "Yes",
						"99.":         "pony express",
						"41.0.":       "Unknown",
						"41.1.":       "a",
						"42.0.":       "Normal",
						"42.1.":       "b",
						"43.0.":       "Problem",
						"43.1.":       "c",
						"44.0.":       "Failure",
						"44.1.":       "e",
						"45.0.":       "Delayed",
						"45.1.":       "f",
						"46.0.":       "Closed",
						"46.1.":       "g",
						"47.0.":       "Early Out",
						"47.1.":       "h",
						"48.0.":       "Unknown",
						"48.1.":       "i",
						"49.0.":       "Unknown",
						"49.1.":       "j",
						"50.0.":       "Unknown",
						"50.1.":       "k",
						"51.0.":       "Unknown",
						"51.1.":       "l",
						"52.0.":       "Unknown",
						"52.1.":       "m",
						"53.0.":       "Unknown",
						"53.1.":       "n",
						"54.0.":       "Unknown",
						"54.1.":       "o",
						"55.0.":       "Unknown",
						"55.1.":       "p",
						"56.0.":       "Unknown",
						"56.1.":       "q",
						"OpRelayRcvd": "rr",
						"OpRelaySent": "rs",
						"OpName":      "Fred Flintstone",
						"OpCall":      "A6AAA",
						"OpDate":      "12/18/2021",
						"OpTime":      "10:51",
					},
				},
				OriginMessageNumber: "AAA-111",
				Date:                "12/18/2021",
				Time:                "12:34",
				DateTime:            time.Date(2021, 12, 18, 12, 34, 0, 0, time.Local),
				HandlingOrder:       pktmsg.HandlingImmediate,
				ToICSPosition:       "topos",
				FromICSPosition:     "frompos",
				ToLocation:          "toloc",
				FromLocation:        "fromloc",
				ToName:              "toname",
				FromName:            "fromname",
				ToContactInfo:       "tocon",
				FromContactInfo:     "fromcon",
				RelayReceived:       "rr",
				RelaySent:           "rs",
				OperatorName:        "Fred Flintstone",
				OperatorCallSign:    "A6AAA",
				OperatorDate:        "12/18/2021",
				OperatorTime:        "10:51",
				OperatorDateTime:    time.Date(2021, 12, 18, 10, 51, 0, 0, time.Local),
			},
			ReportType:                      "Update",
			Jurisdiction:                    "Sunnyvale",
			EOCPhone:                        "1111111111",
			EOCFax:                          "2222222222",
			PrimaryEMContactName:            "pecn",
			PrimaryEMContactPhone:           "3333333333",
			SecondaryEMContactName:          "secn",
			SecondaryEMContactPhone:         "4444444444",
			GovtOfficeStatus:                "Open",
			GovtOfficeExpectedOpenDate:      "01/01/2021",
			GovtOfficeExpectedOpenTime:      "13:00",
			GovtOfficeExpectedOpenDateTime:  time.Date(2021, 1, 1, 13, 0, 0, 0, time.Local),
			GovtOfficeExpectedCloseDate:     "02/02/2021",
			GovtOfficeExpectedCloseTime:     "14:00",
			GovtOfficeExpectedCloseDateTime: time.Date(2021, 2, 2, 14, 0, 0, 0, time.Local),
			EOCIsOpen:                       "Yes",
			EOCActivationLevel:              "Normal",
			EOCExpectedOpenDate:             "03/03/2021",
			EOCExpectedOpenTime:             "15:00",
			EOCExpectedOpenDateTime:         time.Date(2021, 3, 3, 15, 0, 0, 0, time.Local),
			EOCExpectedCloseDate:            "04/04/2021",
			EOCExpectedCloseTime:            "16:00",
			EOCExpectedCloseDateTime:        time.Date(2021, 4, 4, 16, 0, 0, 0, time.Local),
			StateOfEmergency:                "Yes",
			StateOfEmergencySent:            "pony express",
			CommunicationsStatus:            "Unknown",
			CommunicationsComments:          "a",
			DebrisStatus:                    "Normal",
			DebrisComments:                  "b",
			FloodingStatus:                  "Problem",
			FloodingComments:                "c",
			HazmatStatus:                    "Failure",
			HazmatComments:                  "e",
			EmergencyServicesStatus:         "Delayed",
			EmergencyServicesComments:       "f",
			CasualtiesStatus:                "Closed",
			CasualtiesComments:              "g",
			GasUtilitiesStatus:              "Early Out",
			GasUtilitiesComments:            "h",
			ElectricUtilitiesStatus:         "Unknown",
			ElectricUtilitiesComments:       "i",
			PowerInfraStatus:                "Unknown",
			PowerInfraComments:              "j",
			WaterInfraStatus:                "Unknown",
			WaterInfraComments:              "k",
			SewerInfraStatus:                "Unknown",
			SewerInfraComments:              "l",
			SearchRescueStatus:              "Unknown",
			SearchRescueComments:            "m",
			TransportRoadStatus:             "Unknown",
			TransportRoadComments:           "n",
			TransportBridgeStatus:           "Unknown",
			TransportBridgeComments:         "o",
			CivilUnrestStatus:               "Unknown",
			CivilUnrestComments:             "p",
			AnimalIssueStatus:               "Unknown",
			AnimalIssueComments:             "q",
		},
	},
}

func TestParseMessage(t *testing.T) {
	for _, tt := range parseMessageTests {
		t.Run(tt.name, func(t *testing.T) {
			tt.want.Base().RawMessage = tt.rawmsg
			got := pktmsg.ParseMessage(tt.rawmsg)
			if diff := deep.Equal(tt.want, got); diff != nil {
				t.Error(diff)
			}
		})
	}
}
