// Code generated by extract-pifo-fields. DO NOT EDIT.

package racesmar

import "steve.rothskeller.net/packet/xscmsg/internal/xscform"

var formDefinitions = []*xscform.FormDefinition{
	racesmar23,
	racesmar21,
	racesmar16,
}
