// Code generated by extract-pifo-fields. DO NOT EDIT.

package sheltstat

import "steve.rothskeller.net/packet/xscmsg/internal/xscform"

var formDefinitions = []*xscform.FormDefinition{
	sheltstat22,
	sheltstat21,
	sheltstat20,
}
