// Code generated by extract-pifo-fields. DO NOT EDIT.

package eoc213rr

import "github.com/rothskeller/packet/xscmsg/internal/xscform"

var formDefinitions = []*xscform.FormDefinition{
	eoc213rr23,
	eoc213rr21,
	eoc213rr20,
	eoc213rr24,
	eoc213rr23,
}
