package ahfacstat

import (
	"strings"

	"github.com/rothskeller/packet/message/common"
)

// EncodeSubject encodes the message subject.
func (f *AHFacStat) EncodeSubject() string {
	return common.EncodeSubject(f.OriginMsgID, f.Handling, Type.Tag, f.FacilityName)
}

// EncodeBody encodes the message body.
func (f *AHFacStat) EncodeBody() string {
	var (
		sb  strings.Builder
		enc *common.PIFOEncoder
	)
	if f.FormVersion == "" {
		f.FormVersion = "2.3"
	}
	enc = common.NewPIFOEncoder(&sb, "form-allied-health-facility-status.html", f.FormVersion)
	f.StdFields.EncodeHeader(enc)
	enc.Write("19.", f.ReportType)
	enc.Write("20.", f.FacilityName)
	enc.Write("21.", f.FacilityType)
	enc.Write("22d.", f.Date)
	enc.Write("22t.", f.Time)
	enc.Write("23.", f.ContactName)
	enc.Write("23p.", f.ContactPhone)
	enc.Write("23f.", f.ContactFax)
	enc.Write("24.", f.OtherContact)
	enc.Write("25.", f.IncidentName)
	enc.Write("25d.", f.IncidentDate)
	enc.Write("35.", f.FacilityStatus)
	enc.Write("26a.", f.AttachOrgChart)
	enc.Write("26b.", f.AttachRR)
	enc.Write("26c.", f.AttachStatus)
	enc.Write("26d.", f.AttachActionPlan)
	enc.Write("27p.", f.EOCPhone)
	enc.Write("26e.", f.AttachDirectory)
	enc.Write("27f.", f.EOCFax)
	enc.Write("28.", f.LiaisonName)
	enc.Write("34.", f.Summary)
	enc.Write("28p.", f.LiaisonPhone)
	enc.Write("29.", f.InfoOfficerName)
	enc.Write("29p.", f.InfoOfficerPhone)
	enc.Write("29e.", f.InfoOfficerEmail)
	enc.Write("30.", f.ClosedContactName)
	enc.Write("30p.", f.ClosedContactPhone)
	enc.Write("40a.", f.SkilledNursingBedsStaffedM)
	enc.Write("40b.", f.SkilledNursingBedsStaffedF)
	enc.Write("40c.", f.SkilledNursingBedsVacantM)
	enc.Write("40d.", f.SkilledNursingBedsVacantF)
	enc.Write("40e.", f.SkilledNursingBedsSurge)
	enc.Write("30e.", f.ClosedContactEmail)
	enc.Write("41a.", f.AssistedLivingBedsStaffedM)
	enc.Write("41b.", f.AssistedLivingBedsStaffedF)
	enc.Write("41c.", f.AssistedLivingBedsVacantM)
	enc.Write("41d.", f.AssistedLivingBedsVacantF)
	enc.Write("41e.", f.AssistedLivingBedsSurge)
	enc.Write("42a.", f.SubAcuteBedsStaffedM)
	enc.Write("42b.", f.SubAcuteBedsStaffedF)
	enc.Write("42c.", f.SubAcuteBedsVacantM)
	enc.Write("42d.", f.SubAcuteBedsVacantF)
	enc.Write("42e.", f.SubAcuteBedsSurge)
	enc.Write("31a.", f.PatientsToEvacuate)
	enc.Write("43a.", f.AlzheimersBedsStaffedM)
	enc.Write("43b.", f.AlzheimersBedsStaffedF)
	enc.Write("43c.", f.AlzheimersBedsVacantM)
	enc.Write("43d.", f.AlzheimersBedsVacantF)
	enc.Write("43e.", f.AlzheimersBedsSurge)
	enc.Write("31b.", f.PatientsInjuredMinor)
	enc.Write("44a.", f.PedSubAcuteBedsStaffedM)
	enc.Write("44b.", f.PedSubAcuteBedsStaffedF)
	enc.Write("44c.", f.PedSubAcuteBedsVacantM)
	enc.Write("44d.", f.PedSubAcuteBedsVacantF)
	enc.Write("44e.", f.PedSubAcuteBedsSurge)
	enc.Write("31c.", f.PatientsTransferred)
	enc.Write("45a.", f.PsychiatricBedsStaffedM)
	enc.Write("45b.", f.PsychiatricBedsStaffedF)
	enc.Write("45c.", f.PsychiatricBedsVacantM)
	enc.Write("45d.", f.PsychiatricBedsVacantF)
	enc.Write("45e.", f.PsychiatricBedsSurge)
	enc.Write("33.", f.OtherPatientCare)
	enc.Write("46.", f.OtherCareBedsType)
	enc.Write("46a.", f.OtherCareBedsStaffedM)
	enc.Write("46b.", f.OtherCareBedsStaffedF)
	enc.Write("46c.", f.OtherCareBedsVacantM)
	enc.Write("46d.", f.OtherCareBedsVacantF)
	enc.Write("46e.", f.OtherCareBedsSurge)
	enc.Write("50a.", f.DialysisChairs)
	enc.Write("50b.", f.DialysisVacantChairs)
	enc.Write("50c.", f.DialysisFrontStaff)
	enc.Write("50d.", f.DialysisSupportStaff)
	enc.Write("50e.", f.DialysisProviders)
	enc.Write("51a.", f.SurgicalChairs)
	enc.Write("51b.", f.SurgicalVacantChairs)
	enc.Write("51c.", f.SurgicalFrontStaff)
	enc.Write("51d.", f.SurgicalSupportStaff)
	enc.Write("51e.", f.SurgicalProviders)
	enc.Write("52a.", f.ClinicChairs)
	enc.Write("52b.", f.ClinicVacantChairs)
	enc.Write("52c.", f.ClinicFrontStaff)
	enc.Write("52d.", f.ClinicSupportStaff)
	enc.Write("52e.", f.ClinicProviders)
	enc.Write("53a.", f.HomeHealthChairs)
	enc.Write("53b.", f.HomeHealthVacantChairs)
	enc.Write("53c.", f.HomeHealthFrontStaff)
	enc.Write("53d.", f.HomeHealthSupportStaff)
	enc.Write("53e.", f.HomeHealthProviders)
	enc.Write("54a.", f.AdultDayCtrChairs)
	enc.Write("54b.", f.AdultDayCtrVacantChairs)
	enc.Write("54c.", f.AdultDayCtrFrontStaff)
	enc.Write("54d.", f.AdultDayCtrSupportStaff)
	enc.Write("54e.", f.AdultDayCtrProviders)
	f.StdFields.EncodeFooter(enc)
	if err := enc.Close(); err != nil {
		panic(err)
	}
	return sb.String()
}
