// Code generated by extract-pifo-fields. DO NOT EDIT.

package jurisstat

import "steve.rothskeller.net/packet/xscmsg/internal/xscform"

var formDefinitions = []*xscform.FormDefinition{
	jurisstat22,
	jurisstat21,
	jurisstat20,
}
