// Code generated by extract-pifo-fields. DO NOT EDIT.

package jurisstat

import "github.com/rothskeller/packet/xscmsg/internal/xscform"

var formDefinitions = []*xscform.FormDefinition{
	jurisstat22,
	jurisstat21,
	jurisstat20,
}
