package tnc

var tncs = map[string]*TNC{
	"Kantronics KPC-3": {
		Name:                "Kantronics KPC-3",
		CommandPrompt:       "cmd:",
		ConnectedMessage:    "*** CONNECTED",
		DisconnectedMessage: "*** DISCONNECTED",
		PreConnectCommands: []string{
			"INTFACE TERMINAL",
			"CD SOFTWARE",
			"NEWMODE ON",
			"8BITCONV ON",
			"BEACON EVERY 0",
			"SLOTTIME 10",
			"PERSIST 63",
			"PACLEN 128",
			"MAXFRAME 2",
			"FRACK 6",
			"RETRY 8",
			"RESPTIME 5",
			"CHECK 30",
			"TXDELAY 40",
			"XFLOW OFF",
			"SENDPAC $05",
			"CR OFF",
			"PACTIME AFTER 2",
			"CPACTIME ON",
			"STREAMEV OFF",
			"STREAMSW $00",
			"MONITOR OFF",
		},
		PostDisconnectCommands: []string{
			"SENDPAC $0D",
			"CR ON",
			"PACTIME AFTER 10",
			"CPACTIME OFF",
			"STREAMSW $7C",
		},
		MyCallCommand:  "MY",
		ConnectCommand: "C",
	},
	"Kantronics KPC-3 Plus": {
		Name:                "Kantronics KPC-3 Plus",
		CommandPrompt:       "cmd:",
		ConnectedMessage:    "*** CONNECTED",
		DisconnectedMessage: "*** DISCONNECTED",
		PreConnectCommands: []string{
			"INTFACE TERMINAL",
			"CD SOFTWARE",
			"NEWMODE ON",
			"8BITCONV ON",
			"BEACON EVERY 0",
			"SLOTTIME 10",
			"PERSIST 63",
			"PACLEN 128",
			"MAXFRAME 2",
			"FRACK 6",
			"RETRY 8",
			"CHECK 30",
			"TXDELAY 40",
			"XFLOW OFF",
			"SENDPAC $05",
			"CR OFF",
			"PACTIME AFTER 2",
			"CPACTIME ON",
			"STREAMEV OFF",
			"STREAMSW $00",
			"MONITOR OFF",
		},
		PostDisconnectCommands: []string{
			"SENDPAC $0D",
			"CR ON",
			"PACTIME AFTER 10",
			"CPACTIME OFF",
			"STREAMSW $7C",
		},
		MyCallCommand:  "MY",
		ConnectCommand: "C",
	},
	"Kenwood TH-D72A": {
		Name:                "Kenwood TH-D72A",
		CommandPrompt:       "cmd:",
		ConnectedMessage:    "*** CONNECTED",
		DisconnectedMessage: "*** DISCONNECTED",
		PreConnectCommands: []string{
			"NEWMODE ON",
			"8BITCONV ON",
			"BEACON EVERY 0",
			"SLOTTIME 10",
			"PERSIST 63",
			"PPERSIST ON",
			"PACLEN 128",
			"MAXFRAME 1",
			"FRACK 6",
			"RETRY 8",
			"RESPTIME 5",
			"CHECK 30",
			"TXDELAY 40",
			"XFLOW OFF",
			"SENDPAC $05",
			"CR OFF",
			"PACTIME AFTER 2",
			"CPACTIME ON",
			"LOCATION EVERY 0",
			"MONITOR OFF",
		},
		PostDisconnectCommands: []string{
			"SENDPAC $0D",
			"CR ON",
			"PACTIME AFTER 10",
			"CPACTIME OFF",
		},
		MyCallCommand:  "MY",
		ConnectCommand: "C",
	},
	"Kenwood TM-D710A": {
		Name:                "Kenwood TM-D710A",
		CommandPrompt:       "cmd:",
		ConnectedMessage:    "*** CONNECTED",
		DisconnectedMessage: "*** DISCONNECTED",
		PreConnectCommands: []string{
			"NEWMODE ON",
			"8BITCONV ON",
			"BEACON EVERY 0",
			"SLOTTIME 10",
			"PERSIST 63",
			"PPERSIST ON",
			"PACLEN 128",
			"MAXFRAME 2",
			"FRACK 6",
			"RETRY 8",
			"RESPTIME 5",
			"CHECK 30",
			"TXDELAY 40",
			"XFLOW OFF",
			"SENDPAC $05",
			"CR OFF",
			"PACTIME AFTER 2",
			"CPACTIME ON",
			"STREAMSW $00",
			"MONITOR OFF",
		},
		PostDisconnectCommands: []string{
			"SENDPAC $0D",
			"CR ON",
			"PACTIME AFTER 10",
			"CPACTIME OFF",
			"STREAMSW $01",
		},
		MyCallCommand:  "MY",
		ConnectCommand: "C",
	},
	"MFJ-1270C": {
		Name:                "MFJ-1270C",
		CommandPrompt:       "cmd:",
		ConnectedMessage:    "*** CONNECTED",
		DisconnectedMessage: "*** DISCONNECTED",
		PreConnectCommands: []string{
			"NEWMODE ON",
			"AWLEN 8",
			"8BITCONV ON",
			"BEACON EVERY 0",
			"SLOTS 4",
			"PACLEN 128",
			"MAXFRAME 2",
			"FRACK 6",
			"RETRY 8",
			"RESPTIME 5",
			"CHECK 30",
			"TXDELAY 40",
			"XFLOW OFF",
			"SENDPAC $05",
			"CR OFF",
			"PACTIME AFTER 2",
			"CPACTIME ON",
			"STREAMSW $00",
			"MONITOR OFF",
		},
		PostDisconnectCommands: []string{
			"SENDPAC $0D",
			"CR ON",
			"PACTIME AFTER 10",
			"CPACTIME OFF",
			"STREAMSW $7C",
		},
		MyCallCommand:  "MY",
		ConnectCommand: "C",
	},
	"MFJ-1274C": {
		Name:                "MFJ-1274C",
		CommandPrompt:       "cmd:",
		ConnectedMessage:    "*** CONNECTED",
		DisconnectedMessage: "*** DISCONNECTED",
		PreConnectCommands: []string{
			"NEWMODE ON",
			"AWLEN 8",
			"8BITCONV ON",
			"BEACON EVERY 0",
			"SLOTS 4",
			"PACLEN 128",
			"MAXFRAME 2",
			"FRACK 6",
			"RETRY 8",
			"RESPTIME 5",
			"CHECK 30",
			"TXDELAY 40",
			"XFLOW OFF",
			"SENDPAC $05",
			"CR OFF",
			"PACTIME AFTER 2",
			"CPACTIME ON",
			"STREAMSW $00",
			"MONITOR OFF",
		},
		PostDisconnectCommands: []string{
			"SENDPAC $0D",
			"CR ON",
			"PACTIME AFTER 10",
			"CPACTIME OFF",
			"STREAMSW $7C",
		},
		MyCallCommand:  "MY",
		ConnectCommand: "C",
	},
	"OpenTNC": {
		Name:                "OpenTNC",
		CommandPrompt:       "cmd:",
		ConnectedMessage:    "*** CONNECTED",
		DisconnectedMessage: "*** DISCONNECTED",
		PreConnectCommands: []string{
			"SLOTTIME 10",
			"PERSIST 63",
			"PACLEN 128",
			"MAXFRAME 2",
			"FRACK 6",
			"RETRY 8",
			"RESPTIME 5",
			"CHECK 30",
			"TXDELAY 40",
			"SENDPAC $05",
			"CR OFF",
			"PACTIME AFTER 1",
			"CPACTIME ON",
			"MONITOR OFF",
		},
		PostDisconnectCommands: []string{
			"SENDPAC $0D",
			"CR ON",
			"PACTIME AFTER 10",
			"CPACTIME OFF",
		},
		MyCallCommand:  "MY",
		ConnectCommand: "C",
	},
	"TAPR TNC2": {
		Name:                "TAPR TNC2",
		CommandPrompt:       "cmd:",
		ConnectedMessage:    "*** CONNECTED",
		DisconnectedMessage: "*** DISCONNECTED",
		PreConnectCommands: []string{
			"NEWMODE ON",
			"AWLEN 8",
			"8BITCONV ON",
			"BEACON EVERY 0",
			"SLOTS 4",
			"PACLEN 128",
			"MAXFRAME 2",
			"FRACK 6",
			"RETRY 8",
			"RESPTIME 5",
			"CHECK 30",
			"TXDELAY 40",
			"XFLOW OFF",
			"SENDPAC $05",
			"CR OFF",
			"PACTIME AFTER 2",
			"CPACTIME ON",
			"STREAMSW $00",
			"MONITOR OFF",
		},
		PostDisconnectCommands: []string{
			"SENDPAC $0D",
			"CR ON",
			"PACTIME AFTER 10",
			"CPACTIME OFF",
			"STREAMSW $7C",
		},
		MyCallCommand:  "MY",
		ConnectCommand: "C",
	},
	"Timewave PK-96": {
		Name:                "Timewave PK-96",
		CommandPrompt:       "cmd:",
		ConnectedMessage:    "*** CONNECTED",
		DisconnectedMessage: "*** DISCONNECTED",
		PreConnectCommands: []string{
			"EXPERT ON",
			"NEWMODE ON",
			"AWLEN 8",
			"8BITCONV ON",
			"BEACON EVERY 0",
			"SLOTTIME 10",
			"PERSIST 63",
			"PPERSIST ON",
			"PACLEN 128",
			"MAXFRAME 2",
			"FRACK 6",
			"RETRY 8",
			"RESPTIME 5",
			"CHECK 30",
			"TXDELAY 40",
			"XFLOW OFF",
			"SENDPAC $05",
			"ACRPACK OFF",
			"PACTIME AFTER 2",
			"CPACTIME ON",
			"CHSWITCH $00",
			"MCON 0",
		},
		PostDisconnectCommands: []string{
			"SENDPAC $0D",
			"ACRPACK ON",
			"PACTIME AFTER 10",
			"CPACTIME OFF",
			"CHSWITCH $7C",
		},
		MyCallCommand:  "MY",
		ConnectCommand: "C",
		EchoTimeout:    800,
	},
}
