// Code generated by extract-pifo-fields. DO NOT EDIT.

package ahfacstat

import "github.com/rothskeller/packet/xscmsg/internal/xscform"

var formDefinitions = []*xscform.FormDefinition{
	ahfacstat23,
	ahfacstat22,
	ahfacstat21,
	ahfacstat20,
}
