// usage: make-forms-key
//
// make-forms-key creates a digital signature key pair to use when signing
// forms bundles.  It writes the public key into the formsBundlePublicKey
// variable in form/formdefs/pubkey.go (which is overwritten).  It writes the
// private key into the formsBundlePrivateKey variable in
// cmd/sign-forms/pvtkey.go (which is overwritten).  It adds pvtkey.go to
// cmd/sign-forms/.gitignore if it is not already there.
package main

import (
	"bufio"
	"crypto/ed25519"
	"fmt"
	"os"
)

func main() {
	var (
		pub  ed25519.PublicKey
		pvt  ed25519.PrivateKey
		fh   *os.File
		scan *bufio.Scanner
		err  error
	)
	if pub, pvt, err = ed25519.GenerateKey(nil); err != nil {
		goto ERROR
	}
	// Make sure pvtkey.go is in gitignore first.
	if fh, err = os.OpenFile("cmd/sign-forms/.gitignore", os.O_CREATE|os.O_RDWR, 0666); err != nil {
		goto ERROR
	}
	scan = bufio.NewScanner(fh)
	for scan.Scan() {
		if scan.Text() == "pvtkey.go" {
			goto FOUND
		}
	}
	fmt.Fprintln(fh, "pvtkey.go")
FOUND:
	fh.Close()
	// Write pvtkey.go.
	if fh, err = os.Create("cmd/sign-forms/pvtkey.go"); err != nil {
		goto ERROR
	}
	fmt.Fprintf(fh, `// Code generated by make-forms-key.  DO NOT EDIT.
package main

import "crypto/ed25519"

var formsBundlePrivateKey ed25519.PrivateKey = %#v
`, []byte(pvt))
	fh.Close()
	// Write pubkey.go
	if fh, err = os.Create("form/formdefs/pubkey.go"); err != nil {
		goto ERROR
	}
	fmt.Fprintf(fh, `// Code generate by make-forms-key.  DO NOT EDIT.
package formdefs

import "crypto/ed25519"

var formsBundlePublicKey ed25519.PublicKey = %#v
`, []byte(pub))
	fh.Close()
	return

ERROR:
	fmt.Fprintf(os.Stderr, "ERROR: %s\n", err)
	os.Exit(1)

}
