// Code generated by extract-pifo-fields. DO NOT EDIT.

package ics213

import "github.com/rothskeller/packet/xscmsg/internal/xscform"

var formDefinitions = []*xscform.FormDefinition{
	ics213v22,
	ics213v21,
	ics213v20,
}
